version: "3.7"
services:
  mssql:
    build:
        context: ./
        dockerfile: sql_Dockerfile
    networks:
        - gradebook-network
  java:
    build:
      context: ./
      dockerfile: java_Dockerfile
    networks:
      - gradebook-network
    depends_on:
      - mssql
    ports:
      - "8080:8080"

networks:
  gradebook-network:
    driver: bridge
